[project]
name = "scannerdeopcoes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
    "tabulate>=0.9.0",
    "yfinance>=1.0",
]
